# V-Native PS2 Makefile
# Requires PS2SDK

EE_BIN = vsport_ps2.elf
EE_OBJS = main_ps2.o quickjs/quickjs.o quickjs/libregexp.o quickjs/libunicode.o quickjs/cutils.o quickjs/quickjs-libc.o
EE_CFLAGS += -I./quickjs -DCONFIG_VERSION=\"2021-03-27\"
EE_CXXFLAGS += -I./quickjs -DCONFIG_VERSION=\"2021-03-27\"
EE_LIBS = -ldebug -lgskit -ldmakit -lm

all: $(EE_BIN)

clean:
	rm -f $(EE_BIN) $(EE_OBJS)

include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.eeglobal
