// Module 0x1ff3
// Args: _0x469c4f, _0x340ebd, _0x1fff9e

export default (_0x469c4f, _0x340ebd, _0x1fff9e) => {
                'use strict';
                const _0x1ba218 = a0_0x6932;
                var _0x57b309 = this && this['__importDefault'] || function(_0x28c0f8) {
                    const _0xf31443 = _0x1ba218;
                    return _0x28c0f8 && _0x28c0f8[_0xf31443(0x16f1)] ? _0x28c0f8 : {
                        'default': _0x28c0f8
                    };
                };
                Object['defineProperty'](_0x340ebd, '__esModule', {
                    'value': !0x0
                });
                const _0xfb0bd2 = _0x57b309(_0x1fff9e(0x9bda)),
                    _0x4a97fd = _0x57b309(_0x1fff9e(0x7584)),
                    _0x62add3 = _0x57b309(_0x1fff9e(0x3fe3)),
                    _0x4a21b4 = {
                        [_0xfb0bd2['default']['BOSS_GIANT_MIMIC1']]: [{
                            'level': 0x64,
                            'maxHp': 0xa,
                            'speed': 0x96,
                            'power': 0x14,
                            'skills': [_0x4a97fd['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 0x2,
                            'xp': 0x1e,
                            'end': 0x1e,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies',
                            'frameNames': ['Ghoul1_0.png', 'Mudman1_0.png', 'Flower2_0.png', 'Ghost_0.png', 'Milk_0.png', 'ShadeRed_0.png'],
                            'bName': 'Mimic Season One',
                            'bDesc': '',
                            'bPlaces': [_0x62add3['default']['RASH']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0xfb0bd2['default']['BOSS_GIANT_MIMIC2']]: [{
                            'level': 0x64,
                            'maxHp': 0xa,
                            'speed': 0x96,
                            'power': 0x14,
                            'skills': [_0x4a97fd['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 0x2,
                            'xp': 0x1e,
                            'end': 0x1e,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies2',
                            'frameNames': ['Imp_0.png', 'Dullahan0_0.png', 'Devil1_0.png', 'Pile4_0.png', 'PantherSkeleton_0.png'],
                            'bName': 'Mimic Season Two',
                            'bDesc': '',
                            'bPlaces': [_0x62add3['default']['RASH']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0xfb0bd2['default']['BOSS_GIANT_MIMIC3']]: [{
                            'level': 0x64,
                            'maxHp': 0xa,
                            'speed': 0x96,
                            'power': 0x14,
                            'skills': [_0x4a97fd['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 0x2,
                            'xp': 0x1e,
                            'end': 0x1e,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies3',
                            'frameNames': ['Kali1_0.png', 'Armor4_0.png', 'Priest_0.png', 'XLDemon1_0.png', 'largebell_0.png'],
                            'bName': 'Mimic Season Three',
                            'bDesc': '',
                            'bPlaces': [_0x62add3['default']['RASH']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0xfb0bd2['default']['BOSS_XLCRAB_RASH']]: [{
                            'level': 0x1e,
                            'maxHp': 0x28,
                            'speed': 0xbe,
                            'power': 0x1e,
                            'skills': [_0x4a97fd['default']['HPxLevel']],
                            'res_Freeze': 1.1,
                            'res_Rosary': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x1,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 0x1,
                            'xp': 0x32,
                            'passThroughWalls': !0x0,
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'textureName': 'enemies2',
                            'end': 0x16,
                            'frameNames': ['XLCrab_0.png']
                        }],
                        [_0xfb0bd2['default']['BOSS_DRAGOGION']]: [{
                            'level': 0x64,
                            'maxHp': 0x14,
                            'speed': 0x96,
                            'power': 0x32,
                            'skills': [_0x4a97fd['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x1e,
                            'end': 0x14,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies3',
                            'frameNames': ['Dragogion_0.png'],
                            'passThroughWalls': !0x0,
                            'bName': 'Tri-Anchors',
                            'bDesc': '',
                            'bPlaces': [_0x62add3['default']['RASH']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0xfb0bd2['default']['BRIDGE_TRAINEE']]: [{
                            'level': 0x1,
                            'maxHp': 0.5,
                            'speed': 0x8c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x1,
                            'xp': 0x1,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'end': 0x1d,
                            'frameNames': ['HoodieG_0.png'],
                            'alias': {
                                'idleFrameCount': 0x4,
                                'end': 0x1d,
                                'textureName': 'enemies3',
                                'frameNames': ['HoodieY_0.png']
                            }
                        }],
                        [_0xfb0bd2['default']['BRIDGE_MINION']]: [{
                            'level': 0x1,
                            'maxHp': 0x7,
                            'speed': 0x64,
                            'power': 0xa,
                            'knockback': 0.3,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 2.5,
                            'end': 0x1e,
                            'textureName': 'enemiesM',
                            'idleFrameCount': 0x4,
                            'frameNames': ['kamaitachi_0.png'],
                            'alias': {
                                'idleFrameCount': 0x4,
                                'end': 0x1e,
                                'textureName': 'enemiesM',
                                'frameNames': ['raiju_0.png']
                            }
                        }],
                        [_0xfb0bd2['default']['BRIDGE_TETRA']]: [{
                            'level': 0x4,
                            'maxHp': 0xf,
                            'speed': 0xc8,
                            'power': 0x8,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x3,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'end': 0x1d,
                            'frameNames': ['Kali1_0.png', 'Kali1alt_0.png'],
                            'alias': {
                                'idleFrameCount': 0x4,
                                'end': 0x1d,
                                'textureName': 'enemies3',
                                'frameNames': ['Kali2_0.png']
                            }
                        }],
                        [_0xfb0bd2['default']['BRIDGE_ARMOR']]: [{
                            'level': 0x6,
                            'maxHp': 0x14,
                            'speed': 0x8c,
                            'power': 0xf,
                            'knockback': 0x0,
                            'maxKnockback': 0x2,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 2.5,
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'frameNames': ['XLArmor5_0.png'],
                            'alias': {
                                'idleFrameCount': 0x4,
                                'end': 0x1d,
                                'textureName': 'enemies3',
                                'frameNames': ['XLArmor3_0.png']
                            }
                        }],
                        [_0xfb0bd2['default']['XLSWORDIAN_V']]: [{
                            'level': 0x7,
                            'maxHp': 0x46,
                            'speed': 0x190,
                            'power': 0xf,
                            'knockback': 0x0,
                            'maxKnockback': 0x1,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'xp': 0x5,
                            'end': 0x1d,
                            'textureName': 'enemiesM',
                            'idleFrameCount': 0x4,
                            'frameNames': ['Swordian_0.png'],
                            'skills': [_0x4a97fd['default']['FixedDirection'], _0x4a97fd['default']['Medusa']],
                            'passThroughWalls': !0x0,
                            'colliderOverride': {
                                'radius': 0.75,
                                'offsetX': -0xc,
                                'offsetY': 0x8
                            }
                        }],
                        [_0xfb0bd2['default']['XLSWORDIAN_AGGRO']]: [{
                            'level': 0x7,
                            'maxHp': 0x46,
                            'speed': 0x78,
                            'power': 0x14,
                            'knockback': 0x0,
                            'maxKnockback': 0x1,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'xp': 0x5,
                            'end': 0x1d,
                            'textureName': 'enemiesM',
                            'idleFrameCount': 0x4,
                            'frameNames': ['Swordian_0.png'],
                            'colliderOverride': {
                                'radius': 0.75,
                                'offsetX': -0xc,
                                'offsetY': 0x8
                            }
                        }],
                        [_0xfb0bd2['default']['BOSS_XLSWORDIAN']]: [{
                            'level': 0x7,
                            'maxHp': 0xa,
                            'skills': [_0x4a97fd['default']['HPxLevel']],
                            'speed': 0xaa,
                            'power': 0x14,
                            'knockback': 0.1,
                            'maxKnockback': 0x1,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x1e,
                            'end': 0x1d,
                            'textureName': 'enemiesM',
                            'idleFrameCount': 0x4,
                            'frameNames': ['Swordian_0.png'],
                            'colliderOverride': {
                                'radius': 0.75,
                                'offsetX': -0xc,
                                'offsetY': 0x8
                            }
                        }],
                        [_0xfb0bd2['default']['BOSS_XLSWORDIAN_2']]: [{
                            'level': 0x7,
                            'maxHp': 0xa,
                            'skills': [_0x4a97fd['default']['HPxLevel']],
                            'speed': 0xaa,
                            'power': 0x14,
                            'knockback': 0.1,
                            'maxKnockback': 0x1,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'tint': 0xff88ff,
                            'scale': 1.5,
                            'xp': 0x1e,
                            'end': 0x1d,
                            'textureName': 'enemiesM',
                            'idleFrameCount': 0x4,
                            'frameNames': ['Swordian_0.png'],
                            'colliderOverride': {
                                'radius': 0.75,
                                'offsetX': -0xc,
                                'offsetY': 0x8
                            }
                        }],
                        [_0xfb0bd2['default']['BRIDGE_BOSS']]: [{
                            'level': 0x5a,
                            'maxHp': 0x15b3,
                            'speed': 0x96,
                            'power': 0x1e,
                            'res_Freeze': 1.1,
                            'res_Knockback': 0x1,
                            'res_Rosary': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x1,
                            'deathKB': 0x1,
                            'killedAmount': 0x0,
                            'xp': 0x32,
                            'scale': 0x2,
                            'passThroughWalls': !0x0,
                            'frameNames': ['loni_0.png'],
                            'end': 0x1e,
                            'textureName': 'enemiesM',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0
                        }],
                        [_0xfb0bd2['default']['BOSS_DROWNER_RASH']]: [{
                            'level': 0x64,
                            'maxHp': 0x50,
                            'speed': 0x96,
                            'power': 0x32,
                            'skills': [_0x4a97fd['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x1e,
                            'end': 0x1d,
                            'idleFrameCount': 0x8,
                            'textureName': 'enemies2',
                            'frameNames': ['XLDrowner_0.png'],
                            'passThroughWalls': !0x0
                        }],
                        [_0xfb0bd2['default']['BOSS_ENDER_RASH']]: [{
                            'level': 0x64,
                            'maxHp': 0x7f,
                            'speed': 0x96,
                            'power': 0x32,
                            'skills': [_0x4a97fd['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'res_Rosary': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x1e,
                            'end': 0x0,
                            'idleFrameCount': 0x5,
                            'textureName': 'enemies3',
                            'frameNames': ['ender_0.png']
                        }],
                        [_0xfb0bd2['default']['XXLBAT']]: [{
                            'level': 0x80,
                            'maxHp': 0x80,
                            'speed': 0x8c,
                            'power': 0xa,
                            'knockback': 0.1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 0xa,
                            'end': 0xe,
                            'idleFrameCount': 0x4,
                            'scale': 1.28,
                            'textureName': 'enemiesM',
                            'frameNames': ['XXLBat_0.png'],
                            'colliderOverride': {
                                'radius': 0.3,
                                'offsetY': -0xc,
                                'offsetX': 0x0
                            },
                            'bName': 'LV128 GOLDEN BAT',
                            'bDesc': '',
                            'bPlaces': [_0x62add3['default']['GREENACRES']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0xfb0bd2['default']['EX_SCALING_BAT1']]: [{
                            'level': 0x1,
                            'maxHp': 0.1,
                            'speed': 0x8c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x1,
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'textureName': 'enemies',
                            'end': 0x1d,
                            'frameNames': ['Bat1_0.png']
                        }],
                        [_0xfb0bd2['default']['EX_SCALING_BAT2']]: [{
                            'level': 0x1,
                            'maxHp': 0.5,
                            'speed': 0x8c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x1,
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'textureName': 'enemies',
                            'end': 0x1d,
                            'frameNames': ['Bat2_0.png']
                        }],
                        [_0xfb0bd2['default']['EX_SCALING_BAT3']]: [{
                            'level': 0x1,
                            'maxHp': 1.1,
                            'speed': 0x8c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 0x1,
                            'end': 0xc,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies',
                            'frameNames': ['Bat3_0.png']
                        }],
                        [_0xfb0bd2['default']['EX_SCALING_BAT3_YELLOW']]: [{
                            'level': 0x1,
                            'maxHp': 0x4,
                            'speed': 0x8c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 0x2,
                            'end': 0xc,
                            'idleFrameCount': 0x4,
                            'tint': 0xffff00,
                            'textureName': 'enemies',
                            'frameNames': ['Bat3_Color_0.png']
                        }],
                        [_0xfb0bd2['default']['EX_SCALING_BAT3_GREEN']]: [{
                            'level': 0x1,
                            'maxHp': 0x7,
                            'speed': 0x8c,
                            'power': 0x8,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 0x3,
                            'end': 0xc,
                            'idleFrameCount': 0x4,
                            'tint': 0xff00,
                            'textureName': 'enemies',
                            'frameNames': ['Bat3_Color_0.png']
                        }],
                        [_0xfb0bd2['default']['EX_SCALING_BAT3_PURPLE']]: [{
                            'level': 0x1,
                            'maxHp': 0xa,
                            'speed': 0x8c,
                            'power': 0xb,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 0x3,
                            'end': 0xc,
                            'idleFrameCount': 0x4,
                            'tint': 0xff00ff,
                            'textureName': 'enemies',
                            'frameNames': ['Bat3_Color_0.png']
                        }],
                        [_0xfb0bd2['default']['EX_SCALING_XLBAT']]: [{
                            'level': 0xa,
                            'maxHp': 0x1b,
                            'speed': 0x8c,
                            'power': 0xa,
                            'knockback': 0.1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 2.5,
                            'end': 0x11,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies',
                            'frameNames': ['XLBat_0.png'],
                            'colliderOverride': {
                                'radius': 0.3,
                                'offsetY': -0x8,
                                'offsetX': 0x0
                            }
                        }],
                        [_0xfb0bd2['default']['EX_SCALING_XXLBAT']]: [{
                            'level': 0x32,
                            'maxHp': 0x32,
                            'speed': 0x8c,
                            'power': 0xc,
                            'knockback': 0.1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 0xa,
                            'end': 0xe,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemiesM',
                            'frameNames': ['XXLBat_0.png'],
                            'colliderOverride': {
                                'radius': 0.2,
                                'offsetY': -0xc,
                                'offsetX': 0x0
                            }
                        }],
                        [_0xfb0bd2['default']['EX_AXE_BAT3']]: [{
                            'level': 0x1,
                            'maxHp': 0.5,
                            'speed': 0x12c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 0x1,
                            'end': 0x10,
                            'idleFrameCount': 0x4,
                            'passThroughWalls': !0x0,
                            'textureName': 'enemies',
                            'frameNames': ['Bat3_0.png']
                        }],
                        [_0xfb0bd2['default']['EX_DIAMOND']]: [{
                            'level': 0x1,
                            'maxHp': 0x5,
                            'speed': 0x0,
                            'power': 0x1e,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'xp': 0x5,
                            'end': 0x13,
                            'idleFrameCount': 0x2,
                            'passThroughWalls': !0x0,
                            'textureName': 'enemiesM',
                            'frameNames': ['diamondNeutral_0.png'],
                            'colliderOverride': {
                                'radius': 0.4,
                                'offsetX': -0x6,
                                'offsetY': -0x6
                            }
                        }],
                        [_0xfb0bd2['default']['EX_DIAMOND_AXE']]: [{
                            'level': 0x1,
                            'maxHp': 0x5,
                            'speed': 0x12c,
                            'power': 0xa,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'xp': 0x5,
                            'end': 0x13,
                            'idleFrameCount': 0x2,
                            'passThroughWalls': !0x0,
                            'textureName': 'enemiesM',
                            'frameNames': ['diamondNeutral_0.png']
                        }]
                    };
                _0x340ebd['default'] = _0x4a21b4;
            };
