// Module 0x4d17
// Args: _0x55cf0e, _0x55c76e, _0x355a11

export default (_0x55cf0e, _0x55c76e, _0x355a11) => {
                'use strict';
                const _0x18c816 = a0_0x6932;
                var _0x1e3f06 = this && this['__importDefault'] || function(_0x11a5cb) {
                    const _0xbe5d9 = _0x18c816;
                    return _0x11a5cb && _0x11a5cb[_0xbe5d9(0x16f1)] ? _0x11a5cb : {
                        'default': _0x11a5cb
                    };
                };
                Object['defineProperty'](_0x55c76e, '__esModule', {
                    'value': !0x0
                });
                const _0x2487eb = _0x1e3f06(_0x355a11(0xd76a)),
                    _0x423d0a = _0x1e3f06(_0x355a11(0xc42e)),
                    _0x3e6530 = {
                        [_0x423d0a['default']['GEM']]: {
                            'name': 'Experience Gem',
                            'description': 'Increases experience.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'GemBlue.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0x186a0,
                            'value': 0x32,
                            'inTreasures': !0x1,
                            'seen': !0x0
                        },
                        [_0x423d0a['default']['COIN']]: {
                            'name': 'Gold Coin',
                            'description': 'Adds 1 to your gold coins total.',
                            'tips': '',
                            'frameName': 'CoinGold.png',
                            'texture': 'items',
                            'pickedupAmount': 0x0,
                            'rarity': 0x32,
                            'unlocksAt': 0x0,
                            'value': 0x1,
                            'inTreasures': !0x1,
                            'seen': !0x0,
                            'feverMS': 0x1f4
                        },
                        [_0x423d0a['default']['COINBAG1']]: {
                            'name': 'Coin Bag',
                            'description': 'Adds 10 to your gold coins total.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'MoneyBagRed.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0xa,
                            'unlocksAt': 0x0,
                            'inTreasures': !0x1,
                            'value': 0xa,
                            'feverMS': 0x1388
                        },
                        [_0x423d0a['default']['COINBAG2']]: {
                            'name': 'Big Coin Bag',
                            'description': 'Adds 25 to your gold coins total.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'MoneyBagGreen.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0x186a0,
                            'hidden': !0x0,
                            'value': 0x19
                        },
                        [_0x423d0a['default']['COINBAGMAX']]: {
                            'name': 'Rich Coin Bag',
                            'description': 'Adds 100 to your gold coins total.',
                            'tips': 'Drop rate affected by Luck.',
                            'texture': 'items',
                            'frameName': 'MoneyBagColor.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x1,
                            'unlocksAt': 0x5,
                            'value': 0x64,
                            'isRare': !0x0,
                            'feverMS': 0x2710
                        },
                        [_0x423d0a['default']['TREASURE']]: {
                            'name': 'Treasure Chest',
                            'description': 'Awards coins and power ups. Dropped by strong enemies.',
                            'tips': 'Quality affected by Luck.',
                            'texture': 'items',
                            'frameName': 'BoxOpen.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['ROSARY']]: {
                            'name': 'Rosary',
                            'description': 'Destroys all enemies in sight.',
                            'tips': 'Drop rate affected by Luck.',
                            'texture': 'items',
                            'frameName': 'Rosary1.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x1,
                            'unlocksAt': 0x8,
                            'value': 0x0,
                            'isRare': !0x0,
                            'sealable': !0x0
                        },
                        [_0x423d0a['default']['NFT']]: {
                            'name': 'Nduja Fritta',
                            'description': 'Temporarily emits cones of flames. Affected by player stats.',
                            'tips': 'Drop rate affected by Luck.',
                            'texture': 'items',
                            'frameName': 'Nft1.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x1,
                            'unlocksAt': 0x0,
                            'value': 0x0,
                            'isRare': !0x0,
                            'sealable': !0x0
                        },
                        [_0x423d0a['default']['OROLOGION']]: {
                            'name': 'Orologion',
                            'description': 'Freezes all enemies in time for 10 seconds.',
                            'tips': 'Drop rate affected by Luck.',
                            'texture': 'items',
                            'frameName': 'PocketWatch1.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x2,
                            'unlocksAt': 0x4,
                            'value': 0x0,
                            'isRare': !0x0,
                            'sealable': !0x0
                        },
                        [_0x423d0a['default']['VACUUM']]: {
                            'name': 'Vacuum',
                            'description': 'Gathers all experience gems left on the ground.',
                            'tips': 'Drop rate affected by Luck.',
                            'texture': 'items',
                            'frameName': 'Vacuum1.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x2,
                            'unlocksAt': 0xc,
                            'value': 0x0,
                            'isRare': !0x0,
                            'sealable': !0x0
                        },
                        [_0x423d0a['default']['ROAST']]: {
                            'name': 'Floor Chicken',
                            'description': 'Restores 30 health points.',
                            'tips': 'Drop rate affected by Luck.',
                            'texture': 'items',
                            'frameName': 'Roast.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0xc,
                            'unlocksAt': 0x0,
                            'value': 0x1e,
                            'isRare': !0x0,
                            'sealable': !0x0
                        },
                        [_0x423d0a['default']['LITTLEHEART']]: {
                            'name': 'Little Heart',
                            'description': 'Pick up to recover 1 HP.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'HeartMini.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['GILDED']]: {
                            'name': 'Gilded Clover',
                            'description': 'Gathers all gold left on the ground and starts a Gold Fever.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'Gilded0.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x1,
                            'unlocksAt': 0x1e,
                            'inTreasures': !0x1,
                            'value': 0.1,
                            'sealable': !0x0
                        },
                        [_0x423d0a['default']['CLOVER']]: {
                            'name': 'Little Clover',
                            'description': 'Pick up to get 10% luckier.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'Clover2.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0.5,
                            'unlocksAt': 0x0,
                            'inTreasures': !0x1,
                            'value': 0.1,
                            'sealable': !0x0
                        },
                        [_0x423d0a['default']['GOLDFINGER']]: {
                            'name': 'Gold Finger',
                            'description': 'Gives temporary invulnerability, bonus Charm, and minimum Cooldown. Defeat as many enemies as possible to win a prize.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'goldenFinger0.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0.02,
                            'unlocksAt': 0x1e,
                            'inTreasures': !0x1,
                            'value': 0.1,
                            'sealable': !0x0,
                            'requiresItem': _0x423d0a['default']['RELIC_TRISECTION']
                        },
                        [_0x423d0a['default']['WEAPON']]: {
                            'name': 'Weapon',
                            'description': 'NA',
                            'tips': '',
                            'texture': 'items',
                            'frameName': '',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x3e8
                        },
                        [_0x423d0a['default']['STATS_TREASURE_1']]: {
                            'name': '',
                            'description': '1',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'BoxOpen.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['STATS_TREASURE_2']]: {
                            'name': '',
                            'description': '2',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'BoxOpen2.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['STATS_TREASURE_3']]: {
                            'name': '',
                            'description': '3',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'BoxOpen3.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['ALWAYS_COINBAG2']]: {
                            'name': '[Always] Big Coin Bag',
                            'description': 'Adds 25 to your gold coins total.',
                            'tips': 'Always picked, for the rest of the run.',
                            'texture': 'items',
                            'frameName': 'MoneyBagGreen.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0x186a0,
                            'hidden': !0x0,
                            'value': 0x19,
                            'isSpecialOption': !0x0
                        },
                        [_0x423d0a['default']['ALWAYS_ROAST']]: {
                            'name': '[Always] Floor Chicken',
                            'description': 'Restores 30 health points.',
                            'tips': 'Always picked over coins if missing HP, for the rest of the run.',
                            'texture': 'items',
                            'frameName': 'Roast.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0x186a0,
                            'hidden': !0x0,
                            'value': 0x1e,
                            'isSpecialOption': !0x0
                        },
                        [_0x423d0a['default']['DUMMY_LIGHTSOURCE']]: {
                            'name': '',
                            'description': '',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'Brazier1.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['DUMMY_GOLDENEGG_MAX']]: {
                            'name': 'MAX EGGS',
                            'description': 'Spend as much gold as possible to buy Golden Eggs.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'goldenegg.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['DUMMY_REVIVAL']]: {
                            'name': 'Revival',
                            'description': 'Gives +1 Revival for this run.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'TiramisuBite.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x2710
                        },
                        [_0x423d0a['default']['DUMMY_BANISH']]: {
                            'name': 'Banish',
                            'description': 'Gives +1 Banish for this run.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'Banish.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x1f4
                        },
                        [_0x423d0a['default']['DUMMY_SKIP']]: {
                            'name': 'Skip',
                            'description': 'Gives +1 Skip for this run.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'Skip.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x64
                        },
                        [_0x423d0a['default']['DUMMY_REROLL']]: {
                            'name': 'Reroll',
                            'description': 'Gives +1 Reroll for this run.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'Dice.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x3e8
                        },
                        [_0x423d0a['default']['DUMMY_ARC']]: {
                            'name': 'Pick a Card',
                            'description': 'Gives an extra Arcana for this run.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'Tarots.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x4e20
                        },
                        [_0x423d0a['default']['RELIC']]: {
                            'name': '',
                            'description': '',
                            'tips': '',
                            'texture': 'items',
                            'frameName': '',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_GRIMOIRE']]: {
                            'name': 'Grim Grimoire',
                            'description': 'Permanently allows to peek at discovered weapon evolutions and unions from the pause menu.',
                            'tips': '',
                            'achievementTips': ' evolution list.',
                            'texture': 'items',
                            'frameName': 'grimoire.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_GOUDA']]: {
                            'name': 'Ars Gouda',
                            'description': 'Permanently allows to access the list of defeated enemies from the main menu.',
                            'tips': '',
                            'achievementTips': ' Bestiary.',
                            'texture': 'items',
                            'frameName': 'bestiary.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_MAP']]: {
                            'name': 'Milky Way Map',
                            'description': 'Permanently enables the map in the pause menu.',
                            'tips': '',
                            'achievementTips': ' pause menu map.',
                            'texture': 'items',
                            'frameName': 'Map.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_BANGER']]: {
                            'name': 'Magic Banger',
                            'description': 'Permanently allows to change music in stage selection.',
                            'tips': '',
                            'achievementTips': ' Music selection.',
                            'texture': 'items',
                            'frameName': 'banger.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_TEAR']]: {
                            'name': 'Sorceress\' Tears',
                            'description': 'Permanently allows to speed up time in Stage Selection.',
                            'tips': '',
                            'achievementTips': ' Hurry mode.',
                            'texture': 'items',
                            'frameName': 'Tear.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_GLASSMASK']]: {
                            'name': 'Glass Vizard',
                            'description': 'Summons the merchant in all stages.',
                            'tips': '',
                            'achievementTips': ' Merchant.',
                            'texture': 'items',
                            'frameName': 'glassmask.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x2710,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_GOLDENEGG']]: {
                            'name': 'Golden Egg',
                            'description': 'Permanently improves a random stat for the current character, by a tiny amount.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'goldenegg.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x2710,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_NOSEGLASSES']]: {
                            'name': 'Mindbender',
                            'description': 'Permanently allows to change character appearance (where applicable) and maximum weapon loadout.',
                            'tips': '',
                            'achievementTips': ' character customization.',
                            'texture': 'items',
                            'frameName': 'mindbender.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x2710,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_YELLOW']]: {
                            'name': 'Yellow Sign',
                            'description': 'Permanently allows to detect hidden items in all stages.',
                            'tips': '',
                            'achievementTips': ' Hidden stage items.',
                            'texture': 'items',
                            'frameName': 'yellowsign.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_SECRETS']]: {
                            'name': 'Forbidden Scrolls of Morbane',
                            'description': 'Permanently allow you to cast spells and to access the list of secrets from the main menu.',
                            'tips': '',
                            'achievementTips': ' ??? ',
                            'texture': 'items',
                            'frameName': 'scrolls.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x2710,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_GGOSPEL']]: {
                            'name': 'Great Gospel',
                            'description': 'Permanently allows to level up weapons beyond their limit. Can be enabled in Stage Selection.',
                            'tips': '',
                            'achievementTips': ' Limit Break.',
                            'texture': 'items',
                            'frameName': 'ggospel.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_MIRROR']]: {
                            'name': 'Gracia\'s Mirror',
                            'description': '',
                            'tips': '',
                            'achievementTips': 'Inverse mode.',
                            'texture': 'items',
                            'frameName': 'mirror.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_TRUMPET']]: {
                            'name': 'Seventh Trumpet',
                            'description': '',
                            'tips': '',
                            'achievementTips': 'Endless mode.',
                            'texture': 'items',
                            'frameName': 'trumpet.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_MALACHITE']]: {
                            'name': 'Chaos Malachite',
                            'description': 'Allows Mortaccio to morph when reaching Level 80.',
                            'tips': '',
                            'achievementTips': 'Anima of Mortaccio.',
                            'texture': 'items',
                            'frameName': 'cMalachite.png',
                            'collectionFrame': 'frameB_bold.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0,
                            'sealable': !0x0
                        },
                        [_0x423d0a['default']['RELIC_ROSALIA']]: {
                            'name': 'Chaos Rosalia',
                            'description': 'Allows Yatta Cavallo to morph when reaching Level 80.',
                            'tips': '',
                            'achievementTips': 'Yatta Daikarin.',
                            'texture': 'items',
                            'frameName': 'cRosalia.png',
                            'collectionFrame': 'frameB_bold.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0,
                            'sealable': !0x0
                        },
                        [_0x423d0a['default']['RELIC_CHARM']]: {
                            'name': 'Apoplexy',
                            'description': 'Allows to buy the Charm PowerUp.',
                            'tips': '',
                            'achievementTips': 'Charm PowerUp.',
                            'collectionFrame': 'frameB_bold.png',
                            'texture': 'items',
                            'frameName': 'Apoplexy.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_TRISECTION']]: {
                            'name': 'Trisection',
                            'description': 'Allows to enable random events in all stages.',
                            'tips': '',
                            'achievementTips': 'Random Events.',
                            'texture': 'items',
                            'frameName': 'trisection.png',
                            'collectionFrame': 'frameB_bold.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_MAP_AS']]: {
                            'name': 'Astral Stair Map',
                            'description': 'Displays a detailed map when in Astral Stair.',
                            'tips': '',
                            'achievementTips': 'Astral Stair Map.',
                            'collectionFrame': 'frameB_bold.png',
                            'texture': 'items',
                            'frameName': 'Map_AS.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['RELIC_MAP_MS']]: {
                            'name': 'Mt.Moonspell Map',
                            'description': 'Displays a detailed map when in Mt.Moonspell.',
                            'tips': '',
                            'achievementTips': 'Mt.Moonspell Map',
                            'collectionFrame': 'frameB_blue.png',
                            'texture': 'items',
                            'frameName': 'Map_MS.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0,
                            'requiresDLC': _0x2487eb['default']['Moonspell']
                        },
                        [_0x423d0a['default']['RELIC_MAP_FS']]: {
                            'name': 'Lake Foscari Map',
                            'description': 'Displays a detailed map when in Lake Foscari.',
                            'tips': '',
                            'achievementTips': 'Lake Foscari Map',
                            'collectionFrame': 'frameB_green.png',
                            'texture': 'items',
                            'frameName': 'Map_FS.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0,
                            'requiresDLC': _0x2487eb['default']['Foscari']
                        },
                        [_0x423d0a['default']['RELIC_RANDOMAZZO']]: {
                            'name': 'Randomazzo',
                            'description': 'Enables the unlocking and activation of Arcanas.',
                            'tips': '',
                            'achievementTips': ' Arcanas.',
                            'texture': 'items',
                            'frameName': 'Tarots.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x1,
                            'value': 0x0,
                            'isRelic': !0x0
                        },
                        [_0x423d0a['default']['COFFIN']]: {
                            'name': '',
                            'description': '',
                            'tips': '',
                            'achievementTips': '',
                            'texture': 'items',
                            'frameName': 'QuestionMark.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['MERCHANT']]: {
                            'name': '',
                            'description': '',
                            'tips': '',
                            'achievementTips': '',
                            'texture': 'items',
                            'frameName': 'merchant.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['EGGMAN']]: {
                            'name': '',
                            'description': '',
                            'tips': '',
                            'achievementTips': '',
                            'texture': 'items',
                            'frameName': 'merchant2.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['HEALER']]: {
                            'name': '',
                            'description': '',
                            'tips': '',
                            'achievementTips': '',
                            'texture': 'items',
                            'frameName': 'Healer.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['DIRECTER']]: {
                            'name': '',
                            'description': '',
                            'tips': '',
                            'achievementTips': '',
                            'texture': 'items',
                            'frameName': 'Healer.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['PURIFY']]: {
                            'name': 'Flames of Moonspell',
                            'description': 'Permanently remove up to 100 random Golden Egg bonuses. This cannot be undone.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'flame2.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['PURIFY2']]: {
                            'name': 'Lantern of Foscari',
                            'description': 'Permanently removes all Golden Egg bonuses on MoveSpeed. This cannot be undone.',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'f_lantern.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['COSMO_PAVONE']]: {
                            'name': 'Cosmo Pavone',
                            'description': '',
                            'tips': '',
                            'texture': 'items',
                            'frameName': 'flame2.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        },
                        [_0x423d0a['default']['TELEPORTER']]: {
                            'name': '',
                            'description': '',
                            'tips': '',
                            'achievementTips': '',
                            'texture': 'items',
                            'frameName': 'Healer.png',
                            'pickedupAmount': 0x0,
                            'rarity': 0x0,
                            'unlocksAt': 0xf4240,
                            'inTreasures': !0x1,
                            'hidden': !0x0,
                            'value': 0x0
                        }
                    };
                _0x55c76e['default'] = _0x3e6530;
            };
