// Module 0x785e
// Args: _0xd09cd1, _0x7a9b3a, _0xbed04c

export default (_0xd09cd1, _0x7a9b3a, _0xbed04c) => {
                'use strict';
                const _0x503a71 = a0_0x6932;
                var _0x1ccd55 = this && this['__importDefault'] || function(_0x476b26) {
                    const _0x55a3e6 = _0x503a71;
                    return _0x476b26 && _0x476b26[_0x55a3e6(0x16f1)] ? _0x476b26 : {
                        'default': _0x476b26
                    };
                };
                Object['defineProperty'](_0x7a9b3a, '__esModule', {
                    'value': !0x0
                });
                const _0x4ac171 = _0x1ccd55(_0xbed04c(0x54e3)),
                    _0x220328 = {
                        [_0x4ac171['default']['WHIP']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['VAMPIRICA']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }, {
                            'rarity': 0x5,
                            'critChance': 0.025,
                            'max': 0x1
                        }],
                        [_0x4ac171['default']['MAGIC_MISSILE']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x5,
                            'penetrating': 0x1,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['HOLY_MISSILE']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x5,
                            'penetrating': 0x1,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['KNIFE']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x5,
                            'penetrating': 0x1,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['THOUSAND']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x5,
                            'penetrating': 0x1,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['AXE']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x5,
                            'penetrating': 0x1,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['SCYTHE']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['CROSS']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['HEAVENSWORD']]: [{
                            'rarity': 0xa,
                            'power': 0.1
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x5,
                            'critChance': 0.025,
                            'max': 0x1
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['HOLYBOOK']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x2328
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['VESPERS']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x2328
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['FIREBALL']]: [{
                            'rarity': 0xa,
                            'power': 0.1
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['HELLFIRE']]: [{
                            'rarity': 0xa,
                            'power': 0.1
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['GARLIC']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }],
                        [_0x4ac171['default']['VORTEX']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }],
                        [_0x4ac171['default']['HOLYWATER']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x2328
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['BORA']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x2328
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['DIAMOND']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x1770
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['ROCHER']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x1770
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['LIGHTNING']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['LOOP']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['PENTAGRAM']]: [{
                            'rarity': 0xa,
                            'chance': 0.05,
                            'max': 0x1
                        }],
                        [_0x4ac171['default']['SIRE']]: [{
                            'rarity': 0x1,
                            'amount': 0x1
                        }],
                        [_0x4ac171['default']['SILF']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x2328
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['SILF2']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x2328
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['SILF3']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x2328
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['GUNS']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x5,
                            'penetrating': 0x1,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['GUNS2']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x5,
                            'penetrating': 0x1,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['GUNS3']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x5,
                            'penetrating': 0x1,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['GATTI']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x3a98
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['STIGRANGATTI']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x3a98
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['SONG']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x1770
                        }],
                        [_0x4ac171['default']['MANNAGGIA']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x1770
                        }],
                        [_0x4ac171['default']['TRAPANO']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0xbb8
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['TRAPANO2']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0xbb8
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['LANCET']]: [{
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x2710
                        }],
                        [_0x4ac171['default']['CORRIDOR']]: [{
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x2710
                        }],
                        [_0x4ac171['default']['LAUREL']]: [],
                        [_0x4ac171['default']['SHROUD']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['VENTO']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x7d0
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['VENTO2']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x7d0
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['BONE']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x1770
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['BONE2']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x1770
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['CHERRY']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0xa,
                            'chance': 0.05,
                            'max': 0x1
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0xbb8
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['CHERRY2']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0xa,
                            'chance': 0.05,
                            'max': 0x1
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0xbb8
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['CART2']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['FLOWER']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0xbb8
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['LAROBBA']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x3
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x1770
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['TRIASSO1']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0xbb8
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['TRIASSO2']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0xbb8
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['TRIASSO3']]: [{
                            'rarity': 0xa,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0xbb8
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['VICTORY']]: [{
                            'rarity': 0x14,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['JUBILEE']]: [{
                            'rarity': 0x14,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0xa,
                            'speed': 0.05,
                            'max': 0x2
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x7d0
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['MISSPELL']]: [{
                            'rarity': 0x14,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x7d0
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }],
                        [_0x4ac171['default']['MISSPELL2']]: [{
                            'rarity': 0x14,
                            'power': 0.05
                        }, {
                            'rarity': 0xa,
                            'area': 0.025,
                            'max': 0xa
                        }, {
                            'rarity': 0x1,
                            'duration': 0x64,
                            'max': 0x7d0
                        }, {
                            'rarity': 0x1,
                            'amount': 0x1,
                            'max': 0x14
                        }]
                    };
                _0x7a9b3a['default'] = _0x220328;
            };
