// Module 0x5616
// Args: _0x2a8e4b, _0x183622, _0x241651

export default (_0x2a8e4b, _0x183622, _0x241651) => {
                'use strict';
                const _0x365c01 = a0_0x6932;
                var _0x3740de = this && this['__importDefault'] || function(_0x930281) {
                    const _0x211f67 = a0_0x6932;
                    return _0x930281 && _0x930281['__esModule'] ? _0x930281 : {
                        'default': _0x930281
                    };
                };
                Object['defineProperty'](_0x183622, '__esModule', {
                    'value': !0x0
                });
                const _0x442b11 = _0x3740de(_0x241651(0x9bda)),
                    _0x45018d = _0x3740de(_0x241651(0x7584)),
                    _0x20f189 = _0x3740de(_0x241651(0x3fe3)),
                    _0x4a96ac = {
                        [_0x442b11['default']['FS_ANFORA_HP']]: [{
                            'level': 0x1,
                            'maxHp': 0x2,
                            'speed': 0x0,
                            'power': 0x0,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'xp': 0x5,
                            'alpha': 0.9,
                            'tint': 0x777799,
                            'killedAmount': 0x0,
                            'textureName': 'enemiesM',
                            'end': 0x1d,
                            'frameNames': ['H1_0.png', 'H2_0.png']
                        }],
                        [_0x442b11['default']['TRAINEE']]: [{
                            'level': 0x1,
                            'maxHp': 1.5,
                            'speed': 0x8c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x1,
                            'xp': 1.5,
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'end': 0x1d,
                            'frameNames': ['Hoodie_0.png']
                        }],
                        [_0x442b11['default']['TRAINEE_Y']]: [{
                            'level': 0x1,
                            'maxHp': 0.5,
                            'speed': 0x8c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x1,
                            'xp': 0x1,
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'end': 0x1d,
                            'frameNames': ['HoodieY_0.png'],
                            'alias': {
                                'idleFrameCount': 0x4,
                                'end': 0x1d,
                                'textureName': 'enemies3',
                                'frameNames': ['stklDommario_0.png']
                            }
                        }],
                        [_0x442b11['default']['TRAINEE_B']]: [{
                            'level': 0x1,
                            'maxHp': 0.5,
                            'speed': 0x8c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x1,
                            'xp': 0x1,
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'end': 0x1d,
                            'frameNames': ['HoodieB_0.png']
                        }],
                        [_0x442b11['default']['TRAINEE_G']]: [{
                            'level': 0x1,
                            'maxHp': 0x4,
                            'speed': 0x8c,
                            'power': 0x5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x1,
                            'xp': 0x1,
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'end': 0x1d,
                            'frameNames': ['HoodieG_0.png']
                        }],
                        [_0x442b11['default']['TRAINEE_P']]: [{
                            'level': 0x4,
                            'maxHp': 0x12,
                            'speed': 0x96,
                            'power': 0x8,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 2.5,
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'end': 0x1d,
                            'frameNames': ['HoodieP_0.png']
                        }],
                        [_0x442b11['default']['TRAINEE_R']]: [{
                            'level': 0x32,
                            'maxHp': 0xff,
                            'speed': 0x258,
                            'power': 0xff,
                            'knockback': -0.25,
                            'maxKnockback': 0x2,
                            'deathKB': 0x1,
                            'idleFrameCount': 0x4,
                            'feverValue': 0x0,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'end': 0x1d,
                            'frameNames': ['HoodieR_0.png']
                        }],
                        [_0x442b11['default']['TRAINEE_ANY']]: [{
                            'level': 0x1e,
                            'maxHp': 0x8,
                            'speed': 0x78,
                            'power': 0x14,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'res_Freeze': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x1,
                            'deathKB': 0x1,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x19,
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'end': 0x1d,
                            'frameNames': ['HoodieR_0.png', 'HoodieP_0.png', 'HoodieG_0.png', 'HoodieB_0.png', 'HoodieY_0.png'],
                            'bName': 'Reaper Trainee',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bInclude': !0x0,
                            'bHighlight': !0x1
                        }],
                        [_0x442b11['default']['FANGEL1']]: [{
                            'level': 0x1,
                            'maxHp': 0.5,
                            'speed': 0x8c,
                            'power': 0x4,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x1,
                            'frameNames': ['Bat3_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'alias': {
                                'idleFrameCount': 0x5,
                                'end': 0x1d,
                                'textureName': 'enemies3',
                                'frameNames': ['bell1_0.png']
                            }
                        }],
                        [_0x442b11['default']['FANGEL2']]: [{
                            'level': 0x2,
                            'maxHp': 1.5,
                            'speed': 0x64,
                            'power': 0x6,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x2,
                            'frameNames': ['Bat3_0.png'],
                            'scale': 1.5,
                            'end': 0x1d,
                            'textureName': 'enemies',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'alias': {
                                'idleFrameCount': 0x5,
                                'end': 0x1d,
                                'textureName': 'enemies3',
                                'frameNames': ['bell2_0.png']
                            }
                        }],
                        [_0x442b11['default']['FANGEL3']]: [{
                            'level': 0x3,
                            'maxHp': 0xf,
                            'speed': 0x64,
                            'power': 0x7,
                            'knockback': 0x0,
                            'maxKnockback': 0x1,
                            'deathKB': 0x2,
                            'xp': 0x3,
                            'frameNames': ['XLBat_0.png'],
                            'end': 0x11,
                            'textureName': 'enemies',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'alias': {
                                'idleFrameCount': 0x5,
                                'end': 0x1d,
                                'textureName': 'enemies3',
                                'frameNames': ['largebell_0.png']
                            }
                        }],
                        [_0x442b11['default']['KALI1']]: [{
                            'level': 0x3,
                            'maxHp': 0x7,
                            'speed': 0x64,
                            'power': 0x8,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 2.5,
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'frameNames': ['Kali1_0.png', 'Kali1alt_0.png'],
                            'bName': 'Kali',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': [_0x442b11['default']['KALI2']]
                        }],
                        [_0x442b11['default']['ARMOR_SWORD']]: [{
                            'level': 0x3,
                            'maxHp': 0xf,
                            'speed': 0x78,
                            'power': 0xa,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x1,
                            'xp': 1.75,
                            'fireDelay': 0x5dc,
                            'bulletType': _0x442b11['default']['BULLET_2'],
                            'frameNames': ['Armor5_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['KALI2']]: [{
                            'level': 0x4,
                            'maxHp': 0xf,
                            'speed': 0xc8,
                            'power': 0x8,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x3,
                            'frameNames': ['Kali2_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['ARMOR_FIRE']]: [{
                            'level': 0x4,
                            'maxHp': 0xf,
                            'speed': 0x78,
                            'power': 0x8,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x3,
                            'frameNames': ['Armor4_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'bName': 'Archon Fiamma',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['SUCCUBUS']]: [{
                            'level': 0x5,
                            'maxHp': 0x19,
                            'speed': 0x82,
                            'power': 0xa,
                            'knockback': 0.5,
                            'maxKnockback': 0x3,
                            'deathKB': 0x3,
                            'xp': 2.75,
                            'frameNames': ['Succubus2_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'bName': 'Succubus',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['KALI2_FAST']]: [{
                            'level': 0x5,
                            'maxHp': 0x19,
                            'speed': 0xc8,
                            'power': 0x9,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x3,
                            'frameNames': ['Kali2_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['XLARMOR_GREEN']]: [{
                            'level': 0x5,
                            'maxHp': 0x1e,
                            'speed': 0x64,
                            'power': 0xb,
                            'knockback': 0x0,
                            'maxKnockback': 0x1,
                            'deathKB': 0x2,
                            'xp': 0x3,
                            'frameNames': ['XLArmor5_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'bName': 'Archon Rame',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['DEMON']]: [{
                            'level': 0x5,
                            'maxHp': 0x19,
                            'speed': 0x8c,
                            'power': 0xa,
                            'knockback': 0.5,
                            'maxKnockback': 0x3,
                            'deathKB': 0x3,
                            'xp': 2.75,
                            'frameNames': ['Priest_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['DEMON_FAST']]: [{
                            'level': 0x5,
                            'maxHp': 0x19,
                            'speed': 0x118,
                            'power': 0xa,
                            'knockback': 0.5,
                            'maxKnockback': 0x3,
                            'deathKB': 0x3,
                            'xp': 2.75,
                            'frameNames': ['Priest_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'bName': 'Demon priest',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['ANGEL1']]: [{
                            'level': 0x5,
                            'maxHp': 0x1e,
                            'speed': 0x64,
                            'power': 0xb,
                            'knockback': 0x0,
                            'maxKnockback': 0x1,
                            'deathKB': 0x2,
                            'end': 0x1d,
                            'xp': 0x3,
                            'idleFrameCount': 0x5,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'frameNames': ['bell1_0.png', 'bell2_0.png'],
                            'bName': 'Fallen Cherub',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['ANGEL2']]: [{
                            'level': 0x5,
                            'maxHp': 0x19,
                            'speed': 0x118,
                            'power': 0xa,
                            'knockback': 0.5,
                            'maxKnockback': 0x3,
                            'deathKB': 0x3,
                            'end': 0x1d,
                            'xp': 2.75,
                            'frameNames': ['largebell_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x5,
                            'killedAmount': 0x0,
                            'bName': 'Fallen Cherubbo',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['ANGEL3']]: [{
                            'level': 0x6,
                            'maxHp': 0x1e,
                            'speed': 0xa0,
                            'power': 0xf,
                            'knockback': 0x1,
                            'maxKnockback': 0x2,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'xp': 0x3,
                            'end': 0x1d,
                            'idleFrameCount': 0x5,
                            'textureName': 'enemies3',
                            'frameNames': ['angle_0.png'],
                            'bName': 'Fallen Throne',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['XLARMOR_GOLD']]: [{
                            'level': 0x6,
                            'maxHp': 0x1e,
                            'speed': 0x8c,
                            'power': 0xf,
                            'knockback': 0x0,
                            'maxKnockback': 0x2,
                            'deathKB': 0x2,
                            'killedAmount': 0x0,
                            'xp': 2.5,
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'frameNames': ['XLArmor3_0.png'],
                            'bName': 'Archon Oro',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['XLDEMON']]: [{
                            'level': 0x6,
                            'maxHp': 0x1e,
                            'speed': 0xa0,
                            'power': 0xf,
                            'knockback': 0x1,
                            'maxKnockback': 0x2,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'xp': 0x3,
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'frameNames': ['XLDemon1_alt_0.png', 'XLDemon1_0.png'],
                            'bName': 'Demon Beast',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['XLDEMON2']]: [{
                            'level': 0x7,
                            'maxHp': 0x32,
                            'speed': 0x96,
                            'power': 0xf,
                            'knockback': 0x0,
                            'maxKnockback': 0x2,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'xp': 0x3,
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'frameNames': ['XLDemon2_0.png']
                        }],
                        [_0x442b11['default']['XLARCHDEMON']]: [{
                            'level': 0x8,
                            'maxHp': 0x46,
                            'speed': 0x8c,
                            'power': 0x14,
                            'knockback': 0x0,
                            'maxKnockback': 0x2,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'xp': 0x3,
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'frameNames': ['XLDeamon5_0.png'],
                            'bName': 'Archdemon',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['TRINACRIA']]: [{
                            'level': 0x7,
                            'maxHp': 0x46,
                            'speed': 0x8c,
                            'power': 0xf,
                            'knockback': 0x0,
                            'maxKnockback': 0x2,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'xp': 0x3,
                            'frameNames': ['trina_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies2',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0,
                            'bName': 'Trinacria',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bIndex': 0x0,
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': []
                        }],
                        [_0x442b11['default']['BOSS_EYE2']]: [{
                            'level': 0x5,
                            'maxHp': 0x6,
                            'speed': 0xc8,
                            'power': 0xb,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'knockback': 0.5,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x1e,
                            'frameNames': ['eye_0.png'],
                            'end': 0x15,
                            'idleFrameCount': 0x1e,
                            'textureName': 'enemies2',
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['BOSS_FANGEL3']]: [{
                            'level': 0x5,
                            'maxHp': 0x5,
                            'speed': 0x8c,
                            'power': 0xb,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'scale': 1.5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x1e,
                            'frameNames': ['XLBat_0.png'],
                            'end': 0x11,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies',
                            'killedAmount': 0x0,
                            'alias': {
                                'idleFrameCount': 0x5,
                                'end': 0x1d,
                                'textureName': 'enemies3',
                                'frameNames': ['largebell_0.png']
                            }
                        }],
                        [_0x442b11['default']['BOSS_SUCCUBUS']]: [{
                            'level': 0x5,
                            'maxHp': 0x6,
                            'speed': 0x8c,
                            'power': 0xb,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'scale': 1.5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x1e,
                            'frameNames': ['Succubus2_0.png'],
                            'end': 0x1d,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies3',
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['BOSS_XLARMOR_GREEN']]: [{
                            'level': 0x5,
                            'maxHp': 0x7,
                            'speed': 0x8c,
                            'power': 0xb,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'scale': 1.5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x1e,
                            'frameNames': ['XLArmor5_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['BOSS_XLARCHDEMON']]: [{
                            'level': 0x5,
                            'maxHp': 0x8,
                            'speed': 0x8c,
                            'power': 0xb,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'scale': 1.5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x1e,
                            'frameNames': ['XLDeamon5_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies3',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['STAGEKILLER']]: [{
                            'level': 0x63,
                            'maxHp': 0x1,
                            'speed': 0x8c,
                            'power': 0xb,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x3,
                            'frameNames': ['stklAntonio_0.png', 'stklArca_0.png', 'stklChristine_0.png', 'stklConcetta_0.png', 'stklDommario_0.png', 'stklGennaro_0.png', 'stklGiovanna_0.png', 'stklImelda_0.png', 'stklKrochi_0.png', 'stklLama_0.png', 'stklOld3_0.png', 'stklPasqualina_0.png', 'stklPoppea_0.png', 'stklPorta_0.png', 'stklPugnala_0.png', 'stklSuora_0.png'],
                            'end': 0x11,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies3',
                            'killedAmount': 0x0,
                            'bName': 'Stage Killer',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bInclude': !0x0,
                            'bHighlight': !0x0,
                            'bVariants': [_0x442b11['default']['STAGEKILLER2']]
                        }],
                        [_0x442b11['default']['STAGEKILLER2']]: [{
                            'level': 0x63,
                            'maxHp': 1.1,
                            'speed': 0x8c,
                            'power': 0xb,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'scale': 1.5,
                            'knockback': 0x1,
                            'maxKnockback': 0x3,
                            'deathKB': 0x2,
                            'xp': 0x3,
                            'frameNames': ['stklAntonio_0.png', 'stklArca_0.png', 'stklChristine_0.png', 'stklConcetta_0.png', 'stklDommario_0.png', 'stklGennaro_0.png', 'stklGiovanna_0.png', 'stklImelda_0.png', 'stklKrochi_0.png', 'stklLama_0.png', 'stklOld3_0.png', 'stklPasqualina_0.png', 'stklPoppea_0.png', 'stklPorta_0.png', 'stklPugnala_0.png', 'stklSuora_0.png'],
                            'end': 0x11,
                            'idleFrameCount': 0x4,
                            'textureName': 'enemies3',
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['BOSS_TRINACRIA']]: [{
                            'level': 0x1e,
                            'maxHp': 0x19,
                            'speed': 0xd2,
                            'power': 0x1e,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'res_Freeze': 1.1,
                            'res_Rosary': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x1,
                            'deathKB': 0x1,
                            'killedAmount': 0x0,
                            'xp': 0x32,
                            'scale': 0x2,
                            'frameNames': ['trina_0.png'],
                            'end': 0x1d,
                            'textureName': 'enemies2',
                            'idleFrameCount': 0x4,
                            'killedAmount': 0x0
                        }],
                        [_0x442b11['default']['POLTER_GEM_STATIC']]: [{
                            'level': 0x1,
                            'maxHp': 0.5,
                            'speed': 0x0,
                            'power': 0x3,
                            'skills': [_0x45018d['default']['SelfDestruct'], _0x45018d['default']['HPxLevel']],
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x1,
                            'xp': 0x2,
                            'moreX': 0x32,
                            'moreY': 0x3c,
                            'idleFrameCount': 0x2,
                            'passThroughWalls': !0x0,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'end': 0xf,
                            'frameNames': ['Gem1_0.png', 'Gem2_0.png', 'Gem3_0.png']
                        }],
                        [_0x442b11['default']['POLTER_GEM']]: [{
                            'level': 0x1,
                            'maxHp': 0.5,
                            'speed': 0x96,
                            'power': 0x3,
                            'skills': [_0x45018d['default']['SelfDestruct'], _0x45018d['default']['HPxLevel']],
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x1,
                            'xp': 0x2,
                            'moreX': 0x32,
                            'moreY': 0x3c,
                            'idleFrameCount': 0x2,
                            'killedAmount': 0x0,
                            'textureName': 'enemies3',
                            'end': 0xf,
                            'frameNames': ['Gem1_0.png', 'Gem2_0.png', 'Gem3_0.png']
                        }],
                        [_0x442b11['default']['BOSS_XLDEATH']]: [{
                            'level': 0x64,
                            'maxHp': 0xffff,
                            'speed': 0x4b0,
                            'power': 0xffff,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'res_Freeze': 0x1,
                            'res_Rosary': 0x1,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': -0.5,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x0,
                            'end': 0x1d,
                            'idleFrameCount': 0x8,
                            'textureName': 'enemies',
                            'frameNames': ['XLReaper_0.png'],
                            'bName': 'The Reaper',
                            'bDesc': '',
                            'bPlaces': [_0x20f189['default']['FOREST'], _0x20f189['default']['LIBRARY'], _0x20f189['default']['WAREHOUSE'], _0x20f189['default']['TOWER'], _0x20f189['default']['CHAPEL'], _0x20f189['default']['MOLISE'], _0x20f189['default']['SINKING'], _0x20f189['default']['GREENACRES'], _0x20f189['default']['BONEZONE']],
                            'bHighlight': !0x1,
                            'bInclude': !0x0,
                            'bVariants': [_0x442b11['default']['BOSS_XLDEATH2']]
                        }],
                        [_0x442b11['default']['BOSS_XLDEATH2']]: [{
                            'level': 0x64,
                            'maxHp': 0xffff,
                            'speed': 0x4b0,
                            'power': 0xffff,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'res_Freeze': 0x1,
                            'res_Rosary': 0x1,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': -0.5,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x0,
                            'end': 0x1d,
                            'idleFrameCount': 0x8,
                            'passThroughWalls': !0x0,
                            'textureName': 'enemies',
                            'frameNames': ['XLReaper_0.png']
                        }],
                        [_0x442b11['default']['BOSS_TRICKSTER_NORMAL']]: [{
                            'level': 0x64,
                            'maxHp': 0xff,
                            'speed': 0x96,
                            'power': 0x32,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x0,
                            'end': 0x1d,
                            'idleFrameCount': 0x8,
                            'textureName': 'enemies3',
                            'frameNames': ['Trickster_0.png'],
                            'bName': 'The Trickster',
                            'bDesc': 'The fact it can\'t be seen doesn\'t mean it isn\'t there. Can be damaged only in Cappella Magna.',
                            'bPlaces': [_0x20f189['default']['LIBRARY'], _0x20f189['default']['CHAPEL']],
                            'bInclude': !0x0,
                            'bHighlight': !0x1
                        }],
                        [_0x442b11['default']['BOSS_STALKER_NORMAL']]: [{
                            'level': 0x64,
                            'maxHp': 0xff,
                            'speed': 0x96,
                            'power': 0x32,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x0,
                            'end': 0x1d,
                            'idleFrameCount': 0x8,
                            'textureName': 'enemies',
                            'frameNames': ['Stalker_0.png'],
                            'bName': 'The Stalker',
                            'bDesc': 'This one can\'t get the hint. Can be damaged only in Cappella Magna.',
                            'bPlaces': [_0x20f189['default']['WAREHOUSE'], _0x20f189['default']['CHAPEL'], _0x20f189['default']['BONEZONE']],
                            'bInclude': !0x0,
                            'bHighlight': !0x1
                        }],
                        [_0x442b11['default']['BOSS_DROWNER_NORMAL']]: [{
                            'level': 0x64,
                            'maxHp': 0xff,
                            'speed': 0x96,
                            'power': 0x32,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x0,
                            'end': 0x1d,
                            'idleFrameCount': 0x8,
                            'textureName': 'enemies2',
                            'frameNames': ['XLDrowner_0.png'],
                            'passThroughWalls': !0x0,
                            'bName': 'The Drowner',
                            'bDesc': 'Could make it rain for up to 40 days in a row. Can be damaged only in Cappella Magna.',
                            'bPlaces': [_0x20f189['default']['TOWER'], _0x20f189['default']['CHAPEL'], _0x20f189['default']['BONEZONE']],
                            'bHighlight': !0x1,
                            'bInclude': !0x0,
                            'bVariants': [_0x442b11['default']['BOSS_DROWNER_RASH']]
                        }],
                        [_0x442b11['default']['BOSS_MADDENER_NORMAL']]: [{
                            'level': 0x64,
                            'maxHp': 0xff,
                            'speed': 0x96,
                            'power': 0x32,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x0,
                            'end': 0x1d,
                            'idleFrameCount': 0x8,
                            'textureName': 'enemies3',
                            'frameNames': ['Maddener_0.png'],
                            'passThroughWalls': !0x0,
                            'alias': {
                                'idleFrameCount': 0x5,
                                'end': 0x1d,
                                'textureName': 'enemies3',
                                'frameNames': ['angle_0.png']
                            },
                            'bName': 'The Maddener',
                            'bDesc': 'Controls the veil between reality and what lies beyond. Can be damaged only in Cappella Magna.',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bInclude': !0x0,
                            'bHighlight': !0x1
                        }],
                        [_0x442b11['default']['BOSS_ENDER']]: [{
                            'level': 0x64,
                            'maxHp': 0xff,
                            'speed': 0x96,
                            'power': 0x32,
                            'skills': [_0x45018d['default']['HPxLevel']],
                            'res_Freeze': 0x2,
                            'res_Knockback': 0x1,
                            'res_Debuffs': 0x1,
                            'res_Rosary': 0x1,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'killedAmount': 0x0,
                            'scale': 1.5,
                            'xp': 0x0,
                            'end': 0x0,
                            'idleFrameCount': 0x5,
                            'textureName': 'enemies3',
                            'frameNames': ['ender_0.png'],
                            'bName': 'The Ender',
                            'bDesc': 'When the power of friendship goes planet.',
                            'bPlaces': [_0x20f189['default']['CHAPEL']],
                            'bInclude': !0x0,
                            'bHighlight': !0x1,
                            'bVariants': [_0x442b11['default']['BOSS_ENDER_RASH']]
                        }],
                        [_0x442b11['default']['BULLET_SCYTHE']]: [{
                            'level': 0x1,
                            'maxHp': 0.1,
                            'speed': 0x190,
                            'power': 0xa,
                            'skills': [_0x45018d['default']['FixedDirection']],
                            'passThroughWalls': !0x0,
                            'knockback': 0x0,
                            'maxKnockback': 0x0,
                            'deathKB': 0x0,
                            'xp': 0x0,
                            'frameNames': ['Scythe_i01.png'],
                            'end': 0x0,
                            'textureName': 'enemies3',
                            'killedAmount': 0x0
                        }]
                    };
                _0x183622['default'] = _0x4a96ac;
            };
